<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Produk_model extends CI_Model
{
  public $table = 'produk';
  public $id    = 'id_produk';
  public $order = 'DESC';

  function get_all()
  {
    $this->db->join('kategori', 'produk.kat_id = kategori.id_kategori', 'left');
    $this->db->join('subkategori', 'produk.subkat_id = subkategori.id_subkategori', 'left');
    $this->db->join('supersubkategori', 'produk.supersubkat_id = supersubkategori.id_supersubkategori', 'left');
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  function get_all_per_seller()
  {
    $this->db->join('kategori', 'produk.kat_id = kategori.id_kategori', 'left');
    $this->db->join('subkategori', 'produk.subkat_id = subkategori.id_subkategori', 'left');
    $this->db->join('supersubkategori', 'produk.supersubkat_id = supersubkategori.id_supersubkategori', 'left');
    $this->db->join('users', 'produk.uploader = users.id', 'left');
    $this->db->where('uploader', $this->session->userdata('user_id'));
    $this->db->order_by($this->id,$this->order);
    return $this->db->get($this->table)->result();
  }

  function get_combo_produk()
  {
    $data = $this->db->get('produk');
    if($data ->num_rows()>0)
    {
      foreach ($data ->result_array() as $row)
      {
        $result['']= '- Pilih Produk -';
        $result[$row['id_produk']]= $row['judul_produk'];
      }
      return $result;
    }
  }

  function get_all_random()
  {
    $this->db->limit(4);
    $this->db->order_by($this->id, 'random');
    return $this->db->get($this->table)->result();
  }

  function get_all_new_home()
  {
    $this->db->join('users', 'produk.uploader = users.id');
    $this->db->limit(12);
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  function get_all_produk_sidebar()
  {
    $this->db->limit(5);
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  function get_komentar($id)
  {
    $this->db->where('slug_produk', $id);
    $this->db->join('komentar', 'produk.id_produk = komentar.produk_id');
    $this->db->join('users', 'komentar.user_id = users.id');
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where('id_produk', $id);
    return $this->db->get($this->table)->row();
  }

  function get_by_id_front($id)
  {
    $this->db->join('kategori', 'produk.kat_id = kategori.id_kategori', 'left');
    $this->db->join('subkategori', 'produk.subkat_id = subkategori.id_subkategori', 'left');
    $this->db->join('supersubkategori', 'produk.supersubkat_id = supersubkategori.id_supersubkategori', 'left');
    $this->db->join('users', 'produk.uploader = users.id', 'left');
    $this->db->where('id_produk', $id);
    $this->db->or_where('slug_produk', $id);

    return $this->db->get($this->table)->row();
  }
  
  // get data by id
  function get_by_id_iklan_seller($id)
  {
    $this->db->join('users', 'produk.uploader = users.id');
    $this->db->where('slug_produk', $id);
    return $this->db->get($this->table)->row();
  }

  function del_by_id($id)
  {
    $this->db->select("foto, foto_type");
    $this->db->where($this->id,$id);
    return $this->db->get($this->table)->row();
  }

  function get_all_katalog($per_page,$dari)
  {
    $this->db->join('users', 'produk.uploader = users.id');
    $this->db->order_by('id_produk', 'DESC');
    $query = $this->db->get($this->table,$per_page,$dari);
    return $query->result();
  }

  // get total rows
  function total_rows() {
    return $this->db->get($this->table)->num_rows();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // insert data
  function insert_komentar($data)
  {
    $this->db->insert('komentar', $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id,$id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

  // get all
  function get_cari_produk()
  {
    $cari = $this->input->post('cari_produk');

    $this->db->like('judul_produk', $cari);
    $this->db->join('users', 'produk.uploader = users.id');
    return $this->db->get($this->table)->result();
  }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */
